### ISSUE TITLE
Binaries clients missed

### ISSUE THREAD

**Issue by frangdt** [google/grr#594] opened 2018-06-06 18:47 UTC
I just installed GRR  with the Docker version but I can not see the binary clients in order to download them and deploy them. 
![image](https://user-images.githubusercontent.com/7000212/41058758-e7570f8e-69ca-11e8-8559-dd9afdd90903.png)

In the section Manage Binaries - executables, I just can see a none label. 
What is going wrong? 
Thanks

**Comment by demonchild2112** [comment] 2018-06-07 11:45
I'm not able to reproduce this. Did you follow the [installation instructions](https://grr-doc.readthedocs.io/en/stable/installing-grr-server/via-docker.html) for GRR's docker image? Also, it might be helpful if you provided the complete output of the `docker run` command.

**Comment by LunarMongoose** [comment] 2018-06-07 20:49
I would just redo the docker pull. I ran into this once during my testing but also was unable to reproduce. I would do a docker pull from v3.2.2.0 following the installation instructions again. I believe that this is a random error

**Comment by demonchild2112** [comment] 2018-06-11 09:16
Try this:

1. Delete all local containers and images from the `grrdocker/grr` repo
2. Re-run `docker run` with the `v3.2.2.0` image
3. Paste the output of the command here

Also, what OS and docker version are you running?

**Comment by grrrrrrrrr** [comment] 2019-03-25 11:10
Have you ever figured out what the issue was here? I'm going to close this bug for now, let us know if you need more assistance.

**Closed by grrrrrrrrr** 2019-03-25 11:10 UTC
