### ISSUE TITLE
Installation: MySQL DB--Exiting script if not ready 

### ISSUE THREAD

**Issue by weslambert** [google/grr#420] opened 2016-08-16 19:25 UTC
Minor issue, but was wondering if the installation script was supposed to exit if a user chooses not to go ahead with the install (if MySQL is chosen as the DB choice and the DB is not yet ready):

Ex.

```
Step 2: Setting Basic Configuration Parameters
We are now going to configure the server using a bunch of questions.


-=GRR Datastore=-
For GRR to work each GRR server has to be able to communicate with the
datastore.  To do this we need to configure a datastore.


1. SQLite (Default) - This datastore is stored on the local file system. If you
configure GRR to run as non-root be sure to allow that user access to the files.

2. MySQL - This datastore uses MySQL and requires MySQL 5.6 server or later
to be running and a user with the ability to create the GRR database and tables.
The MySQL client binaries are required for use with the MySQLdb python module as
well.

Datastore [1]: 2


***WARNING***

Do not continue until a MySQL server, version 5.6 or greater, is running and a
user with the ability to create the GRR database and tables has been created.
You will need the server, username, password, and database name (if already
created) to continue. If no database has been created this script will attempt
to create the necessary database and tables using the credentials provided.

***WARNING***

Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n
Are you ready to continue?[Yn]: n

```

Thanks,
Wes

**Comment by destijl** [comment] 2016-08-17 18:36
That's (kinda?) by design, the idea is you go fix it in another window and don't have to figure out how to re-run this configuration script, but it's pretty inconvenient now that the script is run as post install in the deb and you might be a ways off from having your DB fully ready to go. 

I think this and the need for additional libraries means we shouldn't have MySQL as a prompted option at all, and instead provide post-install instructions to set it up, referring to them in the script. See my last comment here:
https://github.com/google/grr/issues/404

**Comment by weslambert** [comment] 2016-08-17 22:14
I agree with that comment -- I think it would be best if the MySQL DB component was mentioned/documented as a post-install option as opposed to a prompt in the install script.

Thanks,
Wes

**Comment by demonchild2112** [comment] 2018-06-26 09:14
We've started working on making MySQL the default datastore for GRR. This issue falls within the scope of what we plan on addressing, so I'm closing it as a dup of #604.

**Closed by demonchild2112** 2018-06-26 09:14 UTC
