### ISSUE TITLE
User can approve their own hunt

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#389] opened 2016-06-07 18:46 UTC
Testing on tracking head. I decided to try to request approval for access from my own account. I received a notification on my account that I had requested access, and was able to approve it.

approvers.yaml looks like
```
label: "example"
requester_must_be_authorized: True
num_approvers_required: 1
users:
  - user1
  - user2
  - jessica
```

**Comment by scudette** [comment] 2016-06-07 19:35
Right. By default the requester also counts as an approver. If you want two
different approvers you need to specify approvers required of 2.

**Comment by destijl** [comment] 2016-06-08 17:01
That's true for hunt internals but not client approvals, since it's not what users expect:

Subject says hunt, but it sounds like you're talking about a client approval? approvers.yaml only applies to client approvals.

**Comment by jessicawilsonsc** [comment] 2016-06-08 17:21
Just tested, it works for both client approvals and hunts. 

Also tested on a secondary account I created (lets call it jessica2). Something to note - I did not add jessica2 to the approvers.yaml file I have listed above. However, jessica2 was able to request access to a machine labelled "example" and request that jessica2 approve it. When I received the notification on the jessica2 account, I was successfully able to approve it.

**Comment by jessicawilsonsc** [comment] 2016-06-08 17:23
This is the debug message "DEBUG:2016-06-08 17:22:46,006 api_auth_manager:129] No router ACL rule match for user jessica2. Using default router ApiCallRouterWithApprovalChecksWithRobotAccess"

I followed instructions from this conversation - https://groups.google.com/forum/#!topic/grr-users/3N_2kz0uHec

**Comment by destijl** [comment] 2016-06-08 17:32
I suspect you aren't running the fullaccesscontrol manager, or it's misconfigured. Forget approvers.yaml for the moment, you only need that if you want to apply special rules to a subset of clients. To get two-party approval of all clients you don't need it, so remove it and get fullaccesscontrol manager working first.

**Comment by destijl** [comment] 2016-06-08 17:38
@mbushkov if that advice with the router is correct we need to update the documentation:
https://github.com/google/grr-doc/blob/master/admin.adoc#auditing

**Comment by mbushkov** [comment] 2016-06-08 17:57
@destijl - you're right. Updated the auditing docs: https://github.com/google/grr-doc/commit/3643b0d771165c14c1aa0a1204ac92b3ca8010d7

**Comment by jessicawilsonsc** [comment] 2016-06-08 18:01
At the top of the grr.server.yaml file I do have 
```
AdminUI.webauth_manager: BasicWebAuthManager
API.DefaultRouter: ApiCallRouterWithoutChecks
```

But inside of `Admin UI context:` I have 
```
Datastore.security_manager: FullAccessControlManager
  API.DefaultRouter: ApiCallRouterWithApprovalChecksWithRobotAccess
```

**Comment by mbushkov** [comment] 2016-06-08 18:15
If the logs say "Using default router ApiCallRouterWithApprovalChecksWithRobotAccess", it means the right API call router is used. ApiCallRouterWithApprovalChecksWithRobotAccess does check access to hunts/clients and requires approvals to do that (approvals are checked using FullAccessControlManager).

**Comment by mbushkov** [comment] 2016-06-08 18:16
Do you have ACL.approvers_required set anywhere in the config?

**Comment by jessicawilsonsc** [comment] 2016-06-08 18:18
I do not. Would you recommend I set it in `AdminUI context:` or near the top of `grr.server.yaml`?

**Comment by mbushkov** [comment] 2016-06-08 18:22
Just checking - when you self-approve a client, can you start flows on it, browse VFS, etc?
For hunts - when you self-approve - does GRR allow you to start it?

**Comment by jessicawilsonsc** [comment] 2016-06-08 18:51
The following happens for both my jessica and jessica2 accounts - 

For the client - I only have access when I click my notification, and then it is restricted to browsing the filesystem. When I attempt to update the filesystem it does fail out. As long as I am on that page, I can right click any of the links even though they do have little locks next to them and open them in a new tab. If I right click to start a new flow, when I attempt to launch the flow it does fail out, and tell me I need 2 approvers. 

For the hunt - It allows me to approve and gives me a notification. When click the notification and go to run the hunt, it does error out and ask me for 2 approvers. I attempted to approve it again with the same account, but it still asks for 2 separate approvers.

The above doesn't happen when I follow the appropriate procedure and request access from a separate account.

I did get an info leak (intended maybe, but gives some good info) when jessica2 requested access from jessica for access to a machine they weren't in the `approvers.yaml` for. When jessica approved access, jessica2 gets a message that "Existing authorization request failed:" followed by a list of all the users that can request/approve access. My thought process on that is if I compromised 1 account, I can now see many more accounts available.

**Comment by mbushkov** [comment] 2016-06-08 19:13
It seems that things are (almost) working as intended in your case.

Without having a client approval you can get information about the client (host information), but can't start the flows or do pretty much anything. When you say "I am restricted to browsing filesystem" it sounds like an issue, because it shouldn't happen. Do you see the folders under fs/os? Do you see the actual files?

Hunt can be created without an approval, but can't be started. So the behavior you described is correct. Also, with current ACL model, everybody can see everybody's hunts (including results). The hunts files archive download is restricted to users with a proper hunt approval, though.

**Comment by mbushkov** [comment] 2016-06-08 19:33
As for the info leak issue. In general we don't consider group membership to be sensitive information. If attacker has an access to GRR UI, even without approvals, he/she can get a list of all the clients with all the users on these clients. This means that access to GRR UI should be very well protected.

Approvals system helps in cases when  access to the UI is temporarily compromised (laptop stolen, screen not locked) or when there's just a single compromised user. If somebody can compromise 2 GRR user accounts, then this somebody can do pretty much anything and it's really bad.

This means that: GRR approvals system is used for auditing and as a last line of defense for cases when one GRR user account is temporarily compromised. Access to GRR UI should be restricted and protected by other means no matter if approvals system is used or not.

**Comment by jessicawilsonsc** [comment] 2016-06-08 20:49
When I say browsing the file system, I mean when I click the notification that jessica2 approved jessica2 to access machine1, I am directed to the page for "Browse Virtual Filesystem". I am then able to go through any of the folders and see all of their content that is available. I am not able to refresh any of the folders and I am not able to download anything. 

I understand about the info leak.

**Comment by mbushkov** [comment] 2016-06-13 10:21
Hi Jessica!
I can't reproduce the behavior when you can access "Browse Virtual Filesystem" of the client with a self-approved access. I do the following:
* I am user U. I request an approval for client X, specifying "U" as an approver.
* I get a notification to approve access for a user U to client X. I approve it.
* I get a notification that access to X was approved.
* I click on the notification and get an Unauthorized Access dialog box immediately.

Being able to access the Virtual File System of a self-approved client is not an intended behavior. Can you please click on "Settings" menu item and check what you have for Datastore.security_manager option there? The situation you describe may happen when you have API.DefaultRouter set to ApiCallRouterWithApprovalChecksWithoutRobotAccess (or WithRobotAccess), but have Datastore.security_manager set to anything but FullAccessControlManager (i.e. NullAccessControlManager).

**Comment by jessicawilsonsc** [comment] 2016-06-13 18:45
It is listed as Datastore.security_manager:FullAccessControlManager and API.DefaultRouter:ApiCallRouterWithApprovalChecksWithRobotAccess

**Comment by mbushkov** [comment] 2016-06-15 10:09
Jessica, I think we found the issue. Seems like HTTPDataStore causes the behavior you described.

In the configuration file you set:
```
AdminUI Context:
  Datastore.security_manager: FullAccessControlManager
```

Which means that FullAccessControlManager will be enabled on the AdminUI. But when you use HTTPDataStore, you also need to enable it on the data server. With https://github.com/google/grr/commit/5f4281499c1597bfd5b7c76c8c1053c6b3c50915#diff-fd84b55c3e4be0a83eb785e806865f75R848 we added a special "DataServer Context" for config options that will apply to the data server only.

Please update GRR to the latest Git version and add the following to your config:
```
DataServer Context:
  Datastore.security_manager: FullAccessControlManager
```

Hopefully this should fix the issue. Please confirm that it's indeed so, and I'll update the docs.

**Comment by jessicawilsonsc** [comment] 2016-06-15 18:00
I added the updated and the code as requested in every server within my environment in the `install_data/etc/grr-server.yaml`. 

Unfortunately, I still had the same level of access. After clicking the notification that I was approved (both the new one I generated and the old one I had from previous conversations), I was redirected to the Browse Filesystem page and was able to go through it.

Separate note, I attempted to browse through my logs for my master dataserver to give more detail if I could. However they do not exist. I expected them to be similar to grr-ui.log, or grr-worker.log, but there was no file at all for it. Should I create a separate issue for that?

**Comment by mbushkov** [comment] 2016-06-16 06:45
Jessica, I'll take a further look at the issue and will get back to you soon. As for the logging issue - please create a separate issue for that.

**Comment by mbushkov** [comment] 2016-06-21 11:57
Hi Jessica!
The issue should be fixed now with https://github.com/google/grr/commit/ed3eaa167a198d5c685d2a68c25a4560b23c2725

Also, please disregard my previous comments about adding *Datastore.security_manager: FullAccessControlManager* to *DataServer Context*. You don't need to do this (even more, this is likely to make the system unusable).

The only thing you need is to have this in the config to make ACLs work in the AdminUI is:
```
AdminUI Context:
  Datastore.security_manager: FullAccessControlManager
  API.DefaultRouter: ApiCallRouterWithApprovalChecksWithRobotAccess
```

Can you please check that self-approval doesn't work anymore and that you can't browse the Virtual File System of a self-approved client?

**Comment by jessicawilsonsc** [comment] 2016-06-21 17:50
Yes, that fixed the issue!

**Comment by mbushkov** [comment] 2016-06-21 18:19
Cool, glad to hear that.

**Closed by mbushkov** 2016-06-21 18:19 UTC
