### ISSUE TITLE
IP and MAC addresses not pulled by interrogate on OSX

### ISSUE THREAD

**Issue by atkinsj** [google/grr#642] opened 2018-11-15 22:05 UTC
Hey folks,

Running 3.2.4.3 and an interrogate on macOS 10.13.6 is pulling just interface names, not IP addresses or MAC addresses.

![screen shot 2018-11-15 at 2 05 08 pm](https://user-images.githubusercontent.com/10431664/48584761-81edda80-e8df-11e8-9fb9-26d8fff8bb1b.png)

Is there something I should troubleshoot here / some debug logs I should provide? I'll keep digging on this side.

**Comment by atkinsj** [comment] 2018-11-15 22:39
The IP address is being parsed incorrectly:
https://github.com/google/grr/blob/508ca9bb266765fd4ac6ca48c6b7b341ddf5994a/grr/client/grr_response_client/client_actions/osx/osx.py#L164

should be:

`ip4 = ".".join(map(str, data.contents.sin_addr))` (note use of `str` not `chr` which converts an integer to it's ASCII table character reference, rather than converts it to a string).

**Comment by atkinsj** [comment] 2018-11-15 22:47
Ditto for the MAC address:

https://github.com/google/grr/blob/508ca9bb266765fd4ac6ca48c6b7b341ddf5994a/grr/client/grr_response_client/client_actions/osx/osx.py#L175

This is an example of one way to convert it that is bad and I could spend some more time doing properly if you want:

`":".join(map(hex, data.contents.sdl_data[iflen:iflen + addlen])).replace("0x", "")`

Apologies for not doing these properly and submitting a PR; I figured it would be quicker than engaging legal to go over the CLA. I'll get that set up for next time.

**Comment by atkinsj** [comment] 2018-11-15 22:59
(Also note that IPv6 addresses also use `chr` incorrectly.)

**Comment by grrrrrrrrr** [comment] 2018-11-16 09:54
@mrhania can you have a look? I suspect this might be caused by using Unicode literals.

**Comment by mrhania** [comment] 2018-11-22 14:52
This should fixed in e12f350d4d524. The test coverage is also much better now, so hopefully it all works as expected - feel free to reopen if it does not.

**Closed by mrhania** 2018-11-22 14:52 UTC
