### ISSUE TITLE
"Force Run Cron Job" Button Prompt Non-Functional

### ISSUE THREAD

**Issue by brian-olson** [google/grr#323] opened 2016-01-21 13:12 UTC
I just noticed the "Force Run Cron Job" button no longer prompts the user to verify action. It doesn't seem that the prompt was intentionally removed either since the job doesn't run. Rolling back through the commits it seems the prompt stopped working in 25ee38040644a334116fa7c3961f90241549b341 . 

On my deployment the cronjobs were still running automatically in the background until the 18th of this month. We were about a month behind HEAD at that point. I noticed the issue because "interogate" data wasn't being updated. I'm running HEAD across all systems now but still not functional. I did revert one frontend to the above commit in order to get the prompt to appear. That one system was able to schedule a cronjob for the entire fleet successfully. So there seems to be a UI issue with the prompt and perhaps an issue with cron running in the background. I'm not confident about the background cron part yet, but wanted to get the issue reported.

**Comment by mbushkov** [comment] 2016-01-21 13:19
Brian, thanks for reporting this. We modified cron related code recently: we deprecated Cron.enabled_system_jobs in favour of Cron.disabled_system_jobs. This change may be related to this bug. I'll investigate the issue.

**Comment by brian-olson** [comment] 2016-01-21 13:31
One mistake, 6cb897ccecf5a0629a6166c782f74334e71ca2c9 is where the prompt works. 25ee38040644a334116fa7c3961f90241549b341 does not.

**Comment by mbushkov** [comment] 2016-01-25 14:58
Brian, I committed a fix that makes "Force Run Cron Job" button work again.
I couldn't reproduce the situation when the cron jobs were not running at all. Will look more into it.

**Comment by brian-olson** [comment] 2016-02-05 19:24
The "Force Run Cron Job" button is working again and does kick off the cron job as expected. I've been keeping an eye on the cron jobs and none of the are running automatically any longer. I'm still poking around to see if I can find anything else that has changed but wanted to share the current status.

**Comment by mbushkov** [comment] 2016-02-08 12:14
Brian, thanks for an update. Can you please check what settings do you have
for "Cron.enabled_system_jobs" and "Cron.disabled_system_jobs"? You can
look into your YAML config file, or alternatively, check the "Settings" tab
in the AdminUI.

**Comment by brian-olson** [comment] 2016-02-08 12:27
Absolutely, here's a screenshot of the cron section of "Settings." I'm not
sure what "Cron.active" is, but I'm pretty certain our configs haven't
changed with the exception of removing the private code signing certs from
them. Thanks!

[image: Inline image 1]

**Comment by mbushkov** [comment] 2016-02-08 12:34
Brian, sorry - seems like the screenshot wasn't attached properly.

**Comment by brian-olson** [comment] 2016-02-08 12:38
retry attached.

**Comment by mbushkov** [comment] 2016-02-08 12:55
Either I'm missing something or it seems like GitHub strips the email attachment - I still can't see the image. Can you try attaching it via GitHub web interface?

**Comment by brian-olson** [comment] 2016-02-08 16:08
must be stripping :/

![screen shot 2016-02-08 at 7 24 36 am](https://cloud.githubusercontent.com/assets/6720384/12891053/44e9aa9a-ce54-11e5-8300-9018968864be.png)

**Comment by mbushkov** [comment] 2016-02-08 17:03
Ok, I see the problem now. Unfortunately the version you have has a hardcoded default for Cron.disabled_system_jobs. At the same time, you have Cron.enabled_system_jobs set in the config. Cron.enabled_system_jobs is deprecated in favor of Cron.disabled_system_jobs. But if they are set together, then the exception is raised and nothing works (see https://github.com/google/grr/blob/fb5bfac37aed4bf7c7404e1f3a80911e1de5bcbb/lib/aff4_objects/cronjobs.py#L236). The problem is that this error is not indicated anywhere except for the logs.

The fix: please remove Cron.enabled_system_jobs from the config.

We'll also fix GRR to a) not have a hardcoded default for Cron.disabled_system_jobs b) alert you about the configuration problem via the AdminUI.

**Comment by brian-olson** [comment] 2016-02-09 15:44
That took care of it. Thanks!

**Closed** 2016-03-03 17:09 UTC
Labels: bug
