### ISSUE TITLE
Trying to install GRR on Ubuntu Server

### ISSUE THREAD

**Issue by polymorphikx** [google/grr#346] opened 2016-03-27 13:27 UTC
![2016-03-27_9-21-25](https://cloud.githubusercontent.com/assets/18100344/14065595/68f79b84-f3fe-11e5-9599-d396f7de3c48.jpg)
I'm trying to finish a POC of GRR but I'm stuck on an error I cant seem fix. ive tried doing some of the fixed on the issues already resolve but they have not worked. I included a screenshot of the error inside the VM. let me know if additional information is needed...

OS: Ubuntu Server 14.01.1 (VM on VirtualBox)
Fully updated...clean install nothing else installed on the box.

**Comment by weslambert** [comment] 2016-03-27 13:59
I also received this issue a few days ago from a fresh (and updated) Ubuntu 14.04 server install.

**Comment by scudette** [comment] 2016-03-27 15:39
you need to install the dependencies for building matplotlib. Its telling you that it needs freetype and png so on ubuntu:

```
apt-get install libfreetype6-dev libpng12-dev
```

**Comment by polymorphikx** [comment] 2016-03-27 16:11
@scudette I install the two dependencies as you mentioned and now im only getting the freetype dependency error...

i included another screenshot for reference
![2016-03-27-1_9-21-25](https://cloud.githubusercontent.com/assets/18100344/14066342/fdd121ce-f414-11e5-94bc-f43f28f98d9c.jpg)
.

**Comment by scudette** [comment] 2016-03-27 17:30
depending on your ubuntu version libfreetype might be a different version. Try to find which freetype is available:

```
apt-cache search freetype
```

and look for something like libfreetype and its dev equivalent.

This is specifically a problem with the installation of matplotlib which requires it to be built from source on linux. On windows its not an issue because it already has binary wheels.

Note that we already have a installation script for linux in the vagrant files but you can borrow it to install on a normal system as well. All the required deb packages should be in there:

https://github.com/google/grr/blob/master/vagrant/install_linux.sh#L85

**Comment by destijl** [comment] 2016-03-29 00:57
Thanks for the report. The problem is that pytsk3 is failing to install, @joachimmetz updated the repo on the 27th, so I suspect there's a bug there, @joachimmetz can you take a look? We originally had to use the GIFT dev track in this script, because the stable version didn't have the pieces we needed, but perhaps we can change that now?
https://github.com/google/grr/blob/master/scripts/install_script_ubuntu.sh#L128

Also I think there used to be a good reason why this script wasn't "set -e", but there probably isn't anymore, we should turn that on so the failure happens at the correct place.

This should be a workaround until we can get it fixed (although I haven't tested all the way through):

```
sudo add-apt-repository ppa:gift/stable -y
sudo rm /etc/apt/sources.list.d/gift-dev-trusty.list*
```

Then run the package install line again:
https://github.com/google/grr/blob/master/scripts/install_script_ubuntu.sh#L141

**Comment by weslambert** [comment] 2016-03-29 01:55
I've run the setup as you suggested, but receive the following after setting up grr-server
 and when trying to run "grr_config_updater initialize".

##########################################################################################
     Initialize the configuration, building clients and setting options.
##########################################################################################

Run grr_config_updater initialize [Y/n/a]? Y
#### Running #### grr_config_updater initialize
Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 9, in <module>
    from grr.lib import config_lib
  File "/usr/lib/python2.7/dist-packages/grr/lib/config_lib.py", line 26, in <module>
    from grr.lib import type_info
  File "/usr/lib/python2.7/dist-packages/grr/lib/type_info.py", line 13, in <module>
    from grr.lib import rdfvalue
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalue.py", line 29, in <module>
    from grr.proto import jobs_pb2
  File "/usr/lib/python2.7/dist-packages/grr/proto/jobs_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
#########################################################################################
FAILURE RUNNING: grr_config_updater initialize

Any suggestions would be greatly appreciated!  :)

Thanks,
Wes

**Comment by scudette** [comment] 2016-03-29 02:38
This means that the version used to compile the protobuf is not the same as
the runtime protobuf library. Make sure you have protoc and the python
library the same version.

**Comment by weslambert** [comment] 2016-03-29 02:40
Was able to get the script to complete (after above) after reinstalling protobuf and re-running grr_config_updater_intialize:

```
sudo apt-get remove python-protobuf
sudp pip install protobuf
sudo grr_config_updater_initialize
```

Does it matter that I uninstalled the previous?

Thanks,
Wes

**Comment by polymorphikx** [comment] 2016-03-29 11:35
i performed all the library installs manually and afterwards the install script finished. its working now. all i need to do is change the credentials so i sign in to the webapp...

any ideas how to do that?

**Comment by grrrrrrrrr** [comment] 2016-03-29 11:42
One of the last steps of the install script is running
sudo grr_config_updater initialize

If you have done this already, it asked you for credentials. To change the password, just rerun this command.

**Comment by destijl** [comment] 2016-03-29 17:37
Uninstalling is fine. I'm testing a fix for this now, sorry for the inconvenience. The root cause of this problem was that pytsk3 got renamed to python-pytsk3 in the dev track of the PPA. Short term fix is to move to stable track.

**Closed** 2016-03-29 19:38 UTC

**Comment by destijl** [comment] 2016-03-29 19:42
Turned out we needed the dev PPA for the newer version of the protobuf lib, so I've just changed the package name. Should work now.
