### ISSUE TITLE
Key and IV Missing - Memory Collector

### ISSUE THREAD

**Issue by cybercuffs** [google/grr#262] opened 2015-10-01 18:52 UTC
In memory collector, it is not generating the Key and IV when I select the send to socket action.

**Comment by grrrrrrrrr** [comment] 2015-10-12 11:42
Hm key and iv both show up for me. That is for both, flows and hunts, and under the send_to_socket action. Where do you see those problems exactly?

**Comment by cybercuffs** [comment] 2015-10-13 17:25
It is for both hunts and flows. They key and IV are not populating as they used to be after selecting send_to_socket option in memory collector.

**Comment by mbushkov** [comment] 2015-10-13 18:24
The bug is caused by recent changes in the UI. I'm working on the issue, will submit the fix soon.

**Comment by mbushkov** [comment] 2015-10-14 13:18
This is now fixed by the latest commit. Please check that things are working as expected.

**Closed** 2015-10-14 19:55 UTC

**Comment by cybercuffs** [comment] 2015-10-14 21:08
Great, I see key and iv now there.
