### ISSUE TITLE
32 bit normal agent doesn't work on Windows 2008, but debug agent does.

### ISSUE THREAD

**Issue by devyzr** [google/grr#544] opened 2017-10-24 23:04 UTC
When I tried to install a 32 bit version of the agent (downloaded from the most recent version of GRR, installed from the .deb file) on 32 bit versions of Windows 2008 and Windows 2008 R2 I wasn't able to.

I ran the file both via admin console and by double clicking it, but wasn't able to find the GRR directory in system32 after install or see the GRR process running. I then tried with the dbg_ version of the agent and was able to run it successfully, generating the directory, process and is now reporting to the server.

I'm not sure what other information you would need, but I'm happy to provide it.

**Comment by grrrrrrrrr** [comment] 2018-05-14 11:45
Have you ever found a solution to this problem? The clients are identical so I can't really explain why one works while the other doesn't.

**Comment by devyzr** [comment] 2018-05-15 20:47
Sadly no, and we stopped using GRR a couple months ago, so I'm not sure I'll be able to be of much assistance.

**Comment by grrrrrrrrr** [comment] 2018-05-16 11:33
Ok I'll close this issue then since we can't reproduce. The way forward for you is probably to move off 32 bit Windows 2008 (R2) at some point anyways :)

**Closed by grrrrrrrrr** 2018-05-16 11:33 UTC
