### ISSUE TITLE
Can't fetch artifacts list

### ISSUE THREAD

**Issue by eulmatxlm** [google/grr#733] opened 2019-09-13 09:13 UTC
Hello,

We're running GRR 3.3.0.4 on Ubuntu 18, installed from the .deb
Today we tried the WindowsRegistryFilesAndTransactionLogs ArtifactCollectorFlow.

Since then, we have the following issue when trying to use any of the Artifact flow:
In the Search box, the drop down is no longer available, instead we get the message in the attached screenshot, and in the logs the following traceback. Any idea on how to fix that?

Any help would be appreciated.. thanks!

```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 528, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 309, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_plugins/artifact.py", line 64, in Handle
    reload_datastore_artifacts=True),
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/utils.py", line 85, in NewFunction
    return f(self, *args, **kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/artifact_registry.py", line 399, in GetArtifacts
    results.add(artifact)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/rdfvalue.py", line 218, in __hash__
    "mutation.".format(compatibility.GetName(type(self))))
AssertionError: Usage of Artifact violates Python data model: hash() has changed! Usage of RDFStructs as members of sets or keys of dicts is discouraged. If used anyway, mutating is prohibited, because it causes the hash to change. Be aware that accessing unset fields can trigger a mutation.
```

![Launch Flows](https://user-images.githubusercontent.com/47450440/64850898-9c373880-d616-11e9-8682-f8dbe3781e06.png)

**Comment by eulmatxlm** [comment] 2019-09-13 09:29
Actually, restarting grr-server was enough to clear the error. Would still be nice to know what exactly happened here :-)

**Comment by max-vogler** [comment] 2019-09-16 08:35
This is a duplicate of #729. Restarting the server mitigates the issue temporarily. [Installing from HEAD](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-head-deb.html) (or the upcoming release) fixes the issue.

**Closed by max-vogler** 2019-09-16 08:35 UTC
